FROM python:3.11-slim
ARG PORT
WORKDIR /app

COPY requirements.txt .
RUN pip install uv
RUN uv venv .venv
RUN uv pip install --no-cache-dir -r requirements.txt

COPY secondary_worker/ ./secondary_worker/
COPY api/ ./api/
COPY shared/ ./shared/
COPY start_worker_grpc_server.py .

EXPOSE $PORT

CMD uv run python start_worker_grpc_server.py --port $PORT